# Site settings
# for localhost
port: 2000
title: sysb.AI
email: hello@sysb.ai
# description: > # this means to ignore newlines until "baseurl:"
description: "Access your localhost"
baseurl: "/sysb.AI/" # the subpath of your site, e.g. /blog/
url: "https://www.sysb.ai" # the base hostname & protocol for your site

twitter_username: sysb_ai
github_username: sysb-ai

# Build settings
markdown: kramdown

#### Testing here ####
# https://www.sysb.ai/blog/tips-and-tricks-for-using-curl.html
defaults:
  - scope:
      path: '_posts'
    values:
      permalink: /blog/:title:output_ext
