# Site settings
title: sysb.AI
email: hello@sysb.ai
# description: > # this means to ignore newlines until "baseurl:"
description: "Access your localhost"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.sysb.ai" # the base hostname & protocol for your site

twitter_username: sysb_ai
github_username: sysb-ai

# Build settings
markdown: kramdown

#### Testing here ####
defaults:
  - scope:
      path: '_posts'
    values:
      permalink: /blog/:title:output_ext
      