# Site settings
title: sysb.AI
email: hello@sysb.ai
# description: > # this means to ignore newlines until "baseurl:"
description: "Access your localhost"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.sysb.ai" # the base hostname & protocol for your site

twitter_username: sysb_ai
github_username: sysb-ai

# Build settings
markdown: kramdown


#################################
## Testing here:
include:
  - _pages

defaults:
  - scope:
      path: '_posts'
    values:
      permalink: /blog/:categories/:title:output_ext
# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

include:
  - _pages

permalink: pretty
paginate:  12
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-redirect-from
  - jekyll-sitemap